### ISSUE TITLE
Add options -h (help) and maybe -V (version)

### ISSUE THREAD

**Issue by jirutka** [noocsharp/wayclip#4]
I believe that every CLI utility should support at least `-h` to print a brief help message with the available options.

**Comment by noocsharp** [comment]
I agree, just pushed a commit adding `-h`, and released `0.3`. I think if somebody needs the version, it's probably best to consult the package manager.

I now consider the GitHub repo to just be a mirror, so please prefer the tarball from sr.ht: https://git.sr.ht/~noocsharp/wayclip/archive/0.3.tar.gz

Thanks for packaging `wayclip` for Alpine!
